trigger:
  branches:
    include:
    - refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: macOS-latest
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'client/build'
      ArtifactName: 'drop'
      publishLocation: 'Container'
      StoreAsTar: true
...
